name: Q1_archive_README
run-name: ${{ github.actor }} is testing Q1_archive_README
on: [push]
permissions:
  contents: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Q1_archive_README
        run: cat README.md >> Q1_archive_README.md
      # push
      - name: Q1_archive_README
        run: |
          git config --global user.name Julia123456789037
          git config --global user.email julia037.filia@gmail.com
          git add Q1_archive_README.md
          git commit -m "test push de Q1_archive_README.md"
          git push
