name: Q2_archive_README.md
run-name: ${{ github.actor }} is testing Q2_archive_README.md
on: [push]
permissions:
  contents: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Add name and date to Q2_archive_README.md
        run: |
          echo "Justine Bondu" > Q2_archive_README.md
          echo "Date: $(date '+%d-%m-%Y, %H:%M:%S')" >> Q2_archive_README.md

      - name: Copy README.md content to Q2_archive_README.md
        run: |
          cat README.md >> Q2_archive_README.md

      - name: Commit and push Q2_archive_README.md
        run: |
          git config --global user.name "Julia123456789037"
          git config --global user.email "julia037.filia@gmail.com"
          git add Q2_archive_README.md
          git commit -m "test push de Q2_archive_README.md"
          git push
