name: Q2_archive_README.md
run-name: ${{ github.actor }} is testing Q2_archive_README.md
on: [push]
permissions:
  contents: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: prénom et nom Q2_archive_README.md
        run: echo "Justine Bondu" >> Q2_archive_README.md
      - name: Save date and time to rapport.txt
        run: echo date > Q2_archive_README.md
      - name: prénom et nom Q2_archive_README.md
        run: cat README.md >> Q2_archive_README.md
      # push
      - name: Q2_archive_README.md commmit et push
        run: |
          git config --global user.name Julia123456789037
          git config --global user.email julia037.filia@gmail.com
          git add Q2_archive_README.md
          git commit -m "test push de Q2_archive_README.md"
          git push
