name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
permissions:
  contents: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Q2_archive_README.md
        run: justine bondu > Q2_archive_README.md
        run: date > Q2_archive_README.md
        run: README.md > Q2_archive_README.md
      # push
      - name: Q2_archive_README.md commmit et push
        run: |
          git config --global user.name Julia123456789037
          git config --global user.email julia037.filia@gmail.com
          git add Q2_archive_README.md
          git commit -m "test push de Q2_archive_README.md"
          git push
