name: Q4_archive_date.txt
run-name: ${{ github.actor }} is testing Q4_archive_date.txt
on: [push]
permissions:
  contents: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: prénom et nom et Q4.java Q4_archive_date.txt
        run: echo "Justine Bondu" >> Q4_archive_date.txt
              cat Q4.java >> Q4_archive_date.md
      - name: Append date to Q4_archive_date.txt
        run: echo "Date: $(date '+%d-%m-%Y')" >> Q4_archive_date.txt
      # push
      - name: Q4_archive_date.txt commmit et push
        run: |
          git config --global user.name Julia123456789037
          git config --global user.email julia037.filia@gmail.com
          git add Q4_archive_date.md
          git commit -m "test push de Q4_archive_date.txt"
          git push
