name: Q5_archive_date.txt
run-name: ${{ github.actor }} is testing Q5_archive_date.txt
on: [push]
permissions:
  contents: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: prénom et nom Q5_archive_date.txt
        run: echo "Justine Bondu" >> Q5_archive_date.txt
      - name: ajout de Q5.java dans Q5_archive_date.txt
        run: cat Q5.java >> Q5_archive_date.md
      # push
      - name: Q5_archive_date.txt commmit et push
        run: |
          git config --global user.name Julia123456789037
          git config --global user.email julia037.filia@gmail.com
          git add Q5_archive_date.md
          git commit -m "test push de Q5_archive_date.txt"
          git push
